version: '3'
services:
  decidim:
    image: decidim/decidim:latest-dev
    entrypoint: /usr/local/bin/entrypoint.sh
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    working_dir: "/code"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - bundle:/usr/local/bundle
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    links:
      - pg
      - redis
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  bundle: {}
  pg-data: {}
  redis-data: {}
